server:
  port: 8222
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8555/eureka/ #注册中心访问的地址
    instance:
      prefer-ip-address: true #表示是否将当前服务的ip注册到eureka注册中心上
spring:
  application:
    name: configclient